# Generated by Django 4.2.7 on 2025-09-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_template_delete_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
