# Generated by Django 4.2.7 on 2025-09-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_template_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
