# Generated by Django 4.2.7 on 2025-10-14 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_alter_template_external_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
