# Generated by Django 4.2.7 on 2025-09-21 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title', unique=True)),
                ('description', models.TextField(blank=True)),
                ('template_content', models.TextField(help_text='The template content to deliver to users')),
                ('mailerlite_group_id', models.CharField(help_text='MailerLite group ID for this landing page', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(blank=True, choices=[('implement', 'Looking to implement this in my business'), ('sell_services', 'Looking to sell AI services to other businesses')], max_length=20)),
                ('mailerlite_subscriber_id', models.CharField(blank=True, help_text='MailerLite subscriber ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='landing_pages.landingpage')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('landing_page', 'email')},
            },
        ),
    ]
