# Generated by Django 4.2.7 on 2025-09-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPageSubmission',
        ),
    ]
