# Generated by Django 4.2.7 on 2025-09-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0002_delete_landingpagesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='template_content',
            field=models.TextField(blank=True, help_text='The template content to deliver to users', null=True),
        ),
    ]
