# Generated by Django 4.2.7 on 2025-09-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0003_alter_landingpage_template_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='mailerlite_group_id',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='mailerlite_group_ids',
            field=models.JSONField(default=list, help_text='List of MailerLite group IDs for this landing page'),
        ),
    ]
