# Generated by Django 4.2.7 on 2025-10-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0004_remove_landingpage_mailerlite_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('business_name', models.CharField(max_length=200)),
                ('project_nature', models.TextField()),
                ('budget', models.CharField(max_length=50)),
                ('mailerlite_subscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
