# Generated by Django 4.2.7 on 2025-09-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-created_at', 'name']},
        ),
        migrations.RemoveField(
            model_name='tool',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='rating',
        ),
        migrations.AddField(
            model_name='tool',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tools', to='tools.category'),
        ),
    ]
