# Generated by Django 4.2.7 on 2025-10-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_category_alter_tool_options_remove_tool_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Tool',
                'verbose_name_plural': 'AI Tools',
                'ordering': ['tools_name'],
            },
        ),
    ]
