# Generated by Django 4.2.7 on 2025-10-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_aitool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiTool',
        ),
    ]
