# Generated by Django 4.2.7 on 2025-10-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_delete_aitool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='url',
        ),
        migrations.AddField(
            model_name='tool',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tool',
            name='show_on_site',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Source URL'),
        ),
        migrations.AddField(
            model_name='tool',
            name='website_url',
            field=models.URLField(blank=True, default='', verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
    ]
