# Generated by Django 4.2.7 on 2025-10-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_remove_tool_url_tool_external_id_tool_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated (Manual)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='new_features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
