# Generated by Django 4.2.7 on 2025-10-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_tool_last_updated_tool_new_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='new_features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
