# Generated by Django 4.2.7 on 2025-10-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_rename_and_add_description_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='external_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
