# Generated by Django 4.2.7 on 2025-11-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_clean_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='affiliate_url',
            field=models.URLField(blank=True, default='', verbose_name='Affiliate URL'),
        ),
    ]
