# Generated by Django 4.2.7 on 2025-11-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_tool_affiliate_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['table_order', '-created_at', 'name']},
        ),
        migrations.AddField(
            model_name='tool',
            name='table_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Table View Order'),
        ),
    ]
