# Generated by Django 4.2.7 on 2025-11-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_alter_tool_options_tool_table_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='pricing',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('freemium', 'Freemium'), ('paid', 'Paid'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
