# Generated by Django 4.2.7 on 2025-10-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n8n_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='n8ntemplate',
            name='available_on_website',
            field=models.BooleanField(default=True),
        ),
    ]
