# Generated by Django 4.2.7 on 2025-09-18 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalNewsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('event_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('unranked', 'Unranked'), ('ranked', 'Ranked')], default='unranked', max_length=20)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Canonical News Story',
                'verbose_name_plural': 'Canonical News Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapturedNewsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('source_id', models.IntegerField()),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('published_date', models.DateTimeField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('canonical_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_stories', to='news.canonicalnewsstory')),
            ],
            options={
                'verbose_name': 'Captured News Story',
                'verbose_name_plural': 'Captured News Stories',
                'ordering': ['-captured_at'],
                'unique_together': {('source', 'source_id')},
            },
        ),
    ]
