# Generated by Django 4.2.7 on 2025-09-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_canonicalnewsstory_capturednewsstory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
