# Generated by Django 4.2.7 on 2025-09-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_delete_newsarticle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capturednewsstory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='capturednewsstory',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capturednewsstory',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capturednewsstory',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
