# Generated by Django 4.2.7 on 2025-09-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_capturednewsstory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonicalnewsstory',
            name='event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
