# Generated by Django 4.2.7 on 2025-09-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_canonicalnewsstory_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canonicalnewsstory',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
