# Generated by Django 4.2.7 on 2025-11-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_canonicalnewsstory_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturednewsstory',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
