# Generated by Django 4.2.7 on 2025-12-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_capturednewsstory_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalnewsstory',
            name='show_source',
            field=models.BooleanField(default=False),
        ),
    ]
